// Seed Dataset for SIH Prototype PS26024
// 5 Mines, 20 Zones, 100 Workers, Certificates, Violations, Actions, Alerts, Audit Logs.

export const DEMO_MINES = [
  {
    "mineId": "MINE-01",
    "code": "M01",
    "mineName": "Demo Mine Alpha",
    "location": "Dhanbad Coalfield, Jharkhand",
    "type": "Underground & Opencast",
    "status": "ACTIVE",
    "complianceScore": 88,
    "riskLevel": "LOW",
    "officer": "Rajesh Deshmukh",
    "officerId": "MO-001",
    "workersCount": 20,
    "activeViolations": 1,
    "pendingActions": 1,
    "zones": [
      {
        "zoneId": "Z1",
        "zoneName": "North Shaft"
      },
      {
        "zoneId": "Z2",
        "zoneName": "South Shaft"
      },
      {
        "zoneId": "Z3",
        "zoneName": "Processing Plant"
      },
      {
        "zoneId": "Z4",
        "zoneName": "Substation"
      }
    ]
  },
  {
    "mineId": "MINE-02",
    "code": "M02",
    "mineName": "Demo Mine Beta",
    "location": "Raniganj Basin, West Bengal",
    "type": "Opencast Mining",
    "status": "ACTIVE",
    "complianceScore": 82,
    "riskLevel": "LOW",
    "officer": "Anil Sengupta",
    "officerId": "MO-002",
    "workersCount": 20,
    "activeViolations": 1,
    "pendingActions": 1,
    "zones": [
      {
        "zoneId": "Z1",
        "zoneName": "North Shaft"
      },
      {
        "zoneId": "Z2",
        "zoneName": "South Shaft"
      },
      {
        "zoneId": "Z3",
        "zoneName": "Processing Plant"
      },
      {
        "zoneId": "Z4",
        "zoneName": "Workshop"
      }
    ]
  },
  {
    "mineId": "MINE-03",
    "code": "M03",
    "mineName": "Demo Mine Gamma",
    "location": "Singrauli Coal Belt, Madhya Pradesh",
    "type": "Deep Underground Shaft",
    "status": "NEEDS_ATTENTION",
    "complianceScore": 61,
    "riskLevel": "HIGH",
    "officer": "Rajesh Trivedi",
    "officerId": "MO-003",
    "workersCount": 20,
    "activeViolations": 2,
    "pendingActions": 1,
    "zones": [
      {
        "zoneId": "Z1",
        "zoneName": "North Shaft"
      },
      {
        "zoneId": "Z2",
        "zoneName": "South Shaft"
      },
      {
        "zoneId": "Z3",
        "zoneName": "Processing Plant"
      },
      {
        "zoneId": "Z4",
        "zoneName": "Substation"
      }
    ]
  },
  {
    "mineId": "MINE-04",
    "code": "M04",
    "mineName": "Demo Mine Delta",
    "location": "Korba Industrial Belt, Chhattisgarh",
    "type": "Opencast Mechanized",
    "status": "ACTIVE",
    "complianceScore": 91,
    "riskLevel": "LOW",
    "officer": "Kavita Raman",
    "officerId": "MO-004",
    "workersCount": 20,
    "activeViolations": 0,
    "pendingActions": 0,
    "zones": [
      {
        "zoneId": "Z1",
        "zoneName": "North Shaft"
      },
      {
        "zoneId": "Z2",
        "zoneName": "South Shaft"
      },
      {
        "zoneId": "Z3",
        "zoneName": "Processing Plant"
      },
      {
        "zoneId": "Z4",
        "zoneName": "Workshop"
      }
    ]
  },
  {
    "mineId": "MINE-05",
    "code": "M05",
    "mineName": "Demo Mine Epsilon",
    "location": "Talcher Coalfields, Odisha",
    "type": "Underground Continuous Miner",
    "status": "ACTIVE",
    "complianceScore": 73,
    "riskLevel": "MEDIUM",
    "officer": "Bikram Mohanty",
    "officerId": "MO-005",
    "workersCount": 20,
    "activeViolations": 1,
    "pendingActions": 1,
    "zones": [
      {
        "zoneId": "Z1",
        "zoneName": "North Shaft"
      },
      {
        "zoneId": "Z2",
        "zoneName": "South Shaft"
      },
      {
        "zoneId": "Z3",
        "zoneName": "Processing Plant"
      },
      {
        "zoneId": "Z4",
        "zoneName": "Substation"
      }
    ]
  }
];

export const CERTIFICATE_CATEGORIES = [
  "Electrical Competency Certificate",
  "Mining Safety Training Certificate",
  "First Aid & Emergency Response Certificate",
  "Equipment Operation Certificate",
  "Fire Safety Certificate"
];

export const DEMO_WORKERS = [
  {
    "workerId": "W-10001",
    "name": "Rahul Patil",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0001"
  },
  {
    "workerId": "W-10002",
    "name": "Amit Patil",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0002"
  },
  {
    "workerId": "W-10003",
    "name": "Suresh Patil",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0003"
  },
  {
    "workerId": "W-10004",
    "name": "Vikas Patil",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0004"
  },
  {
    "workerId": "W-10005",
    "name": "Arjun Patil",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0005"
  },
  {
    "workerId": "W-10006",
    "name": "Rahul Shinde",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0006"
  },
  {
    "workerId": "W-10007",
    "name": "Amit Shinde",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0007"
  },
  {
    "workerId": "W-10008",
    "name": "Suresh Shinde",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0008"
  },
  {
    "workerId": "W-10009",
    "name": "Vikas Shinde",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0009"
  },
  {
    "workerId": "W-10010",
    "name": "Arjun Shinde",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0010"
  },
  {
    "workerId": "W-10011",
    "name": "Rahul Jadhav",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0011"
  },
  {
    "workerId": "W-10012",
    "name": "Amit Jadhav",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0012"
  },
  {
    "workerId": "W-10013",
    "name": "Suresh Jadhav",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0013"
  },
  {
    "workerId": "W-10014",
    "name": "Vikas Jadhav",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0014"
  },
  {
    "workerId": "W-10015",
    "name": "Arjun Jadhav",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0015"
  },
  {
    "workerId": "W-10016",
    "name": "Rahul Pawar",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0016"
  },
  {
    "workerId": "W-10017",
    "name": "Amit Pawar",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0017"
  },
  {
    "workerId": "W-10018",
    "name": "Suresh Pawar",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0018"
  },
  {
    "workerId": "W-10019",
    "name": "Vikas Pawar",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0019"
  },
  {
    "workerId": "W-10020",
    "name": "Arjun Pawar",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0020"
  },
  {
    "workerId": "W-10021",
    "name": "Rohan Patil",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0021"
  },
  {
    "workerId": "W-10022",
    "name": "Manoj Patil",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0022"
  },
  {
    "workerId": "W-10023",
    "name": "Kiran Patil",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0023"
  },
  {
    "workerId": "W-10024",
    "name": "Deepak Patil",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0024"
  },
  {
    "workerId": "W-10025",
    "name": "Nitin Patil",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0025"
  },
  {
    "workerId": "W-10026",
    "name": "Rohan Shinde",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0026"
  },
  {
    "workerId": "W-10027",
    "name": "Manoj Shinde",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0027"
  },
  {
    "workerId": "W-10028",
    "name": "Kiran Shinde",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0028"
  },
  {
    "workerId": "W-10029",
    "name": "Deepak Shinde",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0029"
  },
  {
    "workerId": "W-10030",
    "name": "Nitin Shinde",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0030"
  },
  {
    "workerId": "W-10031",
    "name": "Rohan Jadhav",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0031"
  },
  {
    "workerId": "W-10032",
    "name": "Manoj Jadhav",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0032"
  },
  {
    "workerId": "W-10033",
    "name": "Kiran Jadhav",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0033"
  },
  {
    "workerId": "W-10034",
    "name": "Deepak Jadhav",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0034"
  },
  {
    "workerId": "W-10035",
    "name": "Nitin Jadhav",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0035"
  },
  {
    "workerId": "W-10036",
    "name": "Rohan Pawar",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0036"
  },
  {
    "workerId": "W-10037",
    "name": "Manoj Pawar",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0037"
  },
  {
    "workerId": "W-10038",
    "name": "Kiran Pawar",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0038"
  },
  {
    "workerId": "W-10039",
    "name": "Deepak Pawar",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0039"
  },
  {
    "workerId": "W-10040",
    "name": "Nitin Pawar",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0040"
  },
  {
    "workerId": "W-10041",
    "name": "Sameer Patil",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0041"
  },
  {
    "workerId": "W-10042",
    "name": "Prakash Patil",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0042"
  },
  {
    "workerId": "W-10043",
    "name": "Vijay Patil",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0043"
  },
  {
    "workerId": "W-10044",
    "name": "Anil Patil",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0044"
  },
  {
    "workerId": "W-10045",
    "name": "Ravi Patil",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0045"
  },
  {
    "workerId": "W-10046",
    "name": "Sameer Shinde",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0046"
  },
  {
    "workerId": "W-10047",
    "name": "Prakash Shinde",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0047"
  },
  {
    "workerId": "W-10048",
    "name": "Vijay Shinde",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0048"
  },
  {
    "workerId": "W-10049",
    "name": "Anil Shinde",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0049"
  },
  {
    "workerId": "W-10050",
    "name": "Ravi Shinde",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0050"
  },
  {
    "workerId": "W-10051",
    "name": "Sameer Jadhav",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0051"
  },
  {
    "workerId": "W-10052",
    "name": "Prakash Jadhav",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0052"
  },
  {
    "workerId": "W-10053",
    "name": "Vijay Jadhav",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0053"
  },
  {
    "workerId": "W-10054",
    "name": "Anil Jadhav",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0054"
  },
  {
    "workerId": "W-10055",
    "name": "Ravi Jadhav",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0055"
  },
  {
    "workerId": "W-10056",
    "name": "Sameer Pawar",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0056"
  },
  {
    "workerId": "W-10057",
    "name": "Prakash Pawar",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0057"
  },
  {
    "workerId": "W-10058",
    "name": "Vijay Pawar",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0058"
  },
  {
    "workerId": "W-10059",
    "name": "Anil Pawar",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0059"
  },
  {
    "workerId": "W-10060",
    "name": "Ravi Pawar",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0060"
  },
  {
    "workerId": "W-10061",
    "name": "Akash Patil",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0061"
  },
  {
    "workerId": "W-10062",
    "name": "Mahesh Patil",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0062"
  },
  {
    "workerId": "W-10063",
    "name": "Sanjay Patil",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0063"
  },
  {
    "workerId": "W-10064",
    "name": "Pankaj Patil",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0064"
  },
  {
    "workerId": "W-10065",
    "name": "Ajay Patil",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0065"
  },
  {
    "workerId": "W-10066",
    "name": "Akash Shinde",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0066"
  },
  {
    "workerId": "W-10067",
    "name": "Mahesh Shinde",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0067"
  },
  {
    "workerId": "W-10068",
    "name": "Sanjay Shinde",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0068"
  },
  {
    "workerId": "W-10069",
    "name": "Pankaj Shinde",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0069"
  },
  {
    "workerId": "W-10070",
    "name": "Ajay Shinde",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0070"
  },
  {
    "workerId": "W-10071",
    "name": "Akash Jadhav",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0071"
  },
  {
    "workerId": "W-10072",
    "name": "Mahesh Jadhav",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0072"
  },
  {
    "workerId": "W-10073",
    "name": "Sanjay Jadhav",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0073"
  },
  {
    "workerId": "W-10074",
    "name": "Pankaj Jadhav",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0074"
  },
  {
    "workerId": "W-10075",
    "name": "Ajay Jadhav",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0075"
  },
  {
    "workerId": "W-10076",
    "name": "Akash Pawar",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0076"
  },
  {
    "workerId": "W-10077",
    "name": "Mahesh Pawar",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0077"
  },
  {
    "workerId": "W-10078",
    "name": "Sanjay Pawar",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0078"
  },
  {
    "workerId": "W-10079",
    "name": "Pankaj Pawar",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0079"
  },
  {
    "workerId": "W-10080",
    "name": "Ajay Pawar",
    "mineId": "MINE-04",
    "mineName": "Demo Mine Delta",
    "zoneId": "Z4",
    "zoneName": "Workshop",
    "area": "Workshop",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0080"
  },
  {
    "workerId": "W-10081",
    "name": "Neeraj Patil",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0081"
  },
  {
    "workerId": "W-10082",
    "name": "Sachin Patil",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0082"
  },
  {
    "workerId": "W-10083",
    "name": "Gaurav Patil",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0083"
  },
  {
    "workerId": "W-10084",
    "name": "Varun Patil",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0084"
  },
  {
    "workerId": "W-10085",
    "name": "Aditya Patil",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z1",
    "zoneName": "North Shaft",
    "area": "North Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0085"
  },
  {
    "workerId": "W-10086",
    "name": "Neeraj Shinde",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0086"
  },
  {
    "workerId": "W-10087",
    "name": "Sachin Shinde",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0087"
  },
  {
    "workerId": "W-10088",
    "name": "Gaurav Shinde",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0088"
  },
  {
    "workerId": "W-10089",
    "name": "Varun Shinde",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0089"
  },
  {
    "workerId": "W-10090",
    "name": "Aditya Shinde",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z2",
    "zoneName": "South Shaft",
    "area": "South Shaft",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0090"
  },
  {
    "workerId": "W-10091",
    "name": "Neeraj Jadhav",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0091"
  },
  {
    "workerId": "W-10092",
    "name": "Sachin Jadhav",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0092"
  },
  {
    "workerId": "W-10093",
    "name": "Gaurav Jadhav",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0093"
  },
  {
    "workerId": "W-10094",
    "name": "Varun Jadhav",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0094"
  },
  {
    "workerId": "W-10095",
    "name": "Aditya Jadhav",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z3",
    "zoneName": "Processing Plant",
    "area": "Processing Plant",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0095"
  },
  {
    "workerId": "W-10096",
    "name": "Neeraj Pawar",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Electrician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0096"
  },
  {
    "workerId": "W-10097",
    "name": "Sachin Pawar",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Fitter",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0097"
  },
  {
    "workerId": "W-10098",
    "name": "Gaurav Pawar",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Operator",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0098"
  },
  {
    "workerId": "W-10099",
    "name": "Varun Pawar",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Blaster",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0099"
  },
  {
    "workerId": "W-10100",
    "name": "Aditya Pawar",
    "mineId": "MINE-05",
    "mineName": "Demo Mine Epsilon",
    "zoneId": "Z4",
    "zoneName": "Substation",
    "area": "Substation",
    "role": "Technician",
    "status": "ACTIVE",
    "joiningDate": "2023-01-15",
    "bloodGroup": "O+",
    "contact": "+91 98765 0100"
  }
];

export const DEMO_ACCOUNTS = [
  {
    "userId": "INS-001",
    "email": "inspector@mineguard.demo",
    "password": "Inspector@123",
    "name": "Anita Kulkarni",
    "role": "INSPECTOR",
    "designation": "Govt. Statutory Coal Mine Inspector",
    "badge": "INS-001",
    "avatar": "👷‍♂️"
  },
  {
    "userId": "MO-001",
    "email": "officer.alpha@mineguard.demo",
    "password": "Officer@123",
    "name": "Rajesh Deshmukh",
    "role": "OFFICER",
    "designation": "Mine Safety & Compliance Officer",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "badge": "MO-001",
    "avatar": "🧑‍💼"
  },
  {
    "userId": "MG-001",
    "email": "management@mineguard.demo",
    "password": "Management@123",
    "name": "Neha Sharma",
    "role": "MANAGEMENT",
    "designation": "Executive Management",
    "badge": "MG-001",
    "avatar": "🏢"
  },
  {
    "userId": "RA-001",
    "email": "authority@mineguard.demo",
    "password": "Authority@123",
    "name": "Vivek Mehta",
    "role": "AUTHORITY",
    "designation": "Regulatory Regional Director",
    "badge": "RA-001",
    "avatar": "🏛️"
  }
];

export const DEMO_CERTIFICATES = [
  {
    "certificateId": "CERT-2024-0012",
    "workerId": "W-10001",
    "workerName": "Rahul Patil",
    "certificateType": "Electrical Competency Certificate",
    "issueDate": "2022-08-15",
    "expiryDate": "2026-08-15",
    "issuingAuthority": "State Mining Safety Directorate (Demo)",
    "documentUrl": "electrical_competency_patil.pdf",
    "verificationStatus": "EXPIRED",
    "mineId": "MINE-01",
    "zoneId": "Z1",
    "area": "North Shaft"
  },
  {
    "certificateId": "CERT-2024-0013",
    "workerId": "W-10007",
    "workerName": "Amit Shinde",
    "certificateType": "Safety Training Certificate",
    "issueDate": "2024-05-20",
    "expiryDate": "2028-05-20",
    "issuingAuthority": "Central Mining Training Institute (Demo)",
    "documentUrl": "safety_training_shinde.pdf",
    "verificationStatus": "VALID",
    "mineId": "MINE-01",
    "zoneId": "Z2",
    "area": "South Shaft"
  },
  {
    "certificateId": "CERT-2024-0014",
    "workerId": "W-10013",
    "workerName": "Suresh Jadhav",
    "certificateType": "Equipment Operation Certificate",
    "issueDate": "2024-09-10",
    "expiryDate": "2026-09-10",
    "issuingAuthority": "Mining Heavy Machinery Board (Demo)",
    "documentUrl": "heavy_machinery_jadhav.pdf",
    "verificationStatus": "EXPIRING SOON",
    "mineId": "MINE-01",
    "zoneId": "Z3",
    "area": "Processing Plant"
  },
  {
    "certificateId": "CERT-2024-0015",
    "workerId": "W-10019",
    "workerName": "Vikas Pawar",
    "certificateType": "First Aid & Emergency Response Certificate",
    "issueDate": "2024-11-01",
    "expiryDate": "2027-11-01",
    "issuingAuthority": "Mining Medical Corps (Demo)",
    "documentUrl": "first_aid_pawar.pdf",
    "verificationStatus": "VALID",
    "mineId": "MINE-01",
    "zoneId": "Z4",
    "area": "Substation"
  },
  {
    "certificateId": "CERT-2024-0021",
    "workerId": "W-10021",
    "workerName": "Rohan Patil",
    "certificateType": "Electrical Competency Certificate",
    "issueDate": "2022-07-01",
    "expiryDate": "2026-07-01",
    "issuingAuthority": "State Electrical Safety Cell (Demo)",
    "documentUrl": "electrical_patil_beta.pdf",
    "verificationStatus": "EXPIRED",
    "mineId": "MINE-02",
    "zoneId": "Z1",
    "area": "North Shaft"
  },
  {
    "certificateId": "CERT-2024-0041",
    "workerId": "W-10041",
    "workerName": "Sameer Patil",
    "certificateType": "Mining Safety Training Certificate",
    "issueDate": "2023-01-10",
    "expiryDate": "2026-08-01",
    "issuingAuthority": "National Mine Safety Board (Demo)",
    "documentUrl": "safety_sameer_patil.pdf",
    "verificationStatus": "EXPIRED",
    "mineId": "MINE-03",
    "zoneId": "Z1",
    "area": "North Shaft"
  }
];

export const DEMO_INSPECTIONS = [
  {
    "inspectionId": "INSP-2026-001",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "area": "North Shaft",
    "zoneId": "Z1",
    "date": "2026-08-26",
    "inspectionType": "Electrical & Personnel Compliance Safety Inspection",
    "overallResult": "FAILED",
    "inspectorId": "INS-001",
    "inspectorName": "Anita Kulkarni",
    "checklistResults": [
      {
        "id": 1,
        "category": "Safety & Signage",
        "item": "Danger High Voltage signage & isolation barriers in place",
        "status": "PASS",
        "notes": "Visible and illuminated"
      },
      {
        "id": 2,
        "category": "Equipment Safety",
        "item": "Transformer grounding & earth leakage circuit breakers tested",
        "status": "PASS",
        "notes": "Ground resistance nominal"
      },
      {
        "id": 3,
        "category": "Worker Compliance",
        "item": "On-duty personnel possess valid mandatory competency certificate",
        "status": "FAIL",
        "notes": "Electrician Rahul Patil (W-10001) competency certificate expired"
      }
    ],
    "notes": "Statutory compliance evaluation failed due to expired worker competency certification in active North Shaft operation."
  }
];

export const DEMO_VIOLATIONS = [
  {
    "violationId": "VIO-2026-001",
    "mineId": "MINE-01",
    "mineName": "Demo Mine Alpha",
    "area": "North Shaft",
    "zoneId": "Z1",
    "category": "Statutory Certification Breach",
    "severity": "HIGH",
    "workerId": "W-10001",
    "workerName": "Rahul Patil",
    "certificateId": "CERT-2024-0012",
    "description": "Electrician Rahul Patil (W-10001) observed on duty in North Shaft with expired Electrical Competency Certificate (Expired 15-Aug-2026).",
    "reportedBy": "Anita Kulkarni (INS-001)",
    "reportedDate": "2026-08-26",
    "status": "OPEN",
    "evidence": "evidence_cert_scan_001.jpg",
    "riskScore": 86,
    "riskLevel": "HIGH",
    "aiExplanation": "High risk calculated due to technical electrical duties assigned with an expired competency credential in an underground shaft.",
    "inspectionId": "INSP-2026-001"
  },
  {
    "violationId": "VIO-2026-002",
    "mineId": "MINE-02",
    "mineName": "Demo Mine Beta",
    "area": "Workshop",
    "zoneId": "Z4",
    "category": "Equipment Maintenance Safety Defect",
    "severity": "MEDIUM",
    "workerId": "W-10036",
    "workerName": "Rohan Pawar",
    "description": "Heavy dumper D-08 reverse safety alarm non-functional during workshop inspection.",
    "reportedBy": "Anita Kulkarni (INS-001)",
    "reportedDate": "2026-08-20",
    "status": "OPEN",
    "evidence": "dumper_alarm_defect.jpg",
    "riskScore": 64,
    "riskLevel": "MEDIUM",
    "aiExplanation": "Moderate risk due to mechanical equipment safety sensor defect in heavy haulage area.",
    "inspectionId": null
  },
  {
    "violationId": "VIO-2026-003",
    "mineId": "MINE-03",
    "mineName": "Demo Mine Gamma",
    "area": "Substation",
    "zoneId": "Z4",
    "category": "Ventilation & Environmental Hazard",
    "severity": "CRITICAL",
    "workerId": "W-10056",
    "workerName": "Sameer Pawar",
    "description": "Deep shaft continuous methane monitoring sensor calibration overdue by 45 days.",
    "reportedBy": "Anita Kulkarni (INS-001)",
    "reportedDate": "2026-08-18",
    "status": "OPEN",
    "evidence": "methane_sensor_log.pdf",
    "riskScore": 92,
    "riskLevel": "CRITICAL",
    "aiExplanation": "Critical risk flagged due to uncalibrated gas sensors in underground hazardous zone.",
    "inspectionId": null
  }
];

export const DEMO_CORRECTIVE_ACTIONS = [
  {
    "actionId": "CA-2026-001",
    "violationId": "VIO-2026-001",
    "mineId": "MINE-01",
    "title": "Obtain & Register Renewed Competency Certification (Rahul Patil)",
    "description": "Remediate violation VIO-2026-001 in North Shaft: Submit renewed statutory competency certification document for worker Rahul Patil.",
    "assignedTo": "Rahul Patil & Mine Alpha Safety Desk",
    "dueDate": "2026-08-30",
    "priority": "HIGH",
    "status": "IN PROGRESS",
    "createdDate": "2026-08-26",
    "completionNotes": "Worker completed renewal exam. Certificate submitted to safety officer for registration.",
    "evidence": null
  },
  {
    "actionId": "CA-2026-002",
    "violationId": "VIO-2026-002",
    "mineId": "MINE-02",
    "title": "Repair Equipment Safety Interlock & Reverse Siren",
    "description": "Replace faulty audio-visual warning siren on Dumper D-08 in Beta Workshop.",
    "assignedTo": "Beta Mechanical Maintenance Team",
    "dueDate": "2026-08-28",
    "priority": "MEDIUM",
    "status": "IN PROGRESS",
    "createdDate": "2026-08-21",
    "completionNotes": null,
    "evidence": null
  }
];

export const DEMO_ALERTS = [
  {
    "alertId": "ALT-101",
    "mineId": "MINE-01",
    "violationId": "VIO-2026-001",
    "title": "High Risk Violation Reported",
    "message": "High risk compliance breach (Score 86/100) reported in Demo Mine Alpha (North Shaft). Action required.",
    "severity": "HIGH",
    "timestamp": "2026-08-26 14:32:10",
    "isRead": false
  },
  {
    "alertId": "ALT-102",
    "mineId": "MINE-03",
    "violationId": "VIO-2026-003",
    "title": "Critical Ventilation Safety Hazard",
    "message": "Critical safety breach (Score 92/100) flagged in Demo Mine Gamma. Sensor calibration overdue.",
    "severity": "CRITICAL",
    "timestamp": "2026-08-18 11:15:00",
    "isRead": false
  }
];

export const DEMO_AUDIT_TRAIL = [
  {
    "auditId": "AUD-901",
    "timestamp": "2026-08-26 14:32:10",
    "actor": "Anita Kulkarni (INS-001)",
    "role": "Inspector",
    "action": "REPORT_VIOLATION",
    "details": "Logged Violation VIO-2026-001 for Demo Mine Alpha regarding expired Electrical Competency Certificate (Rahul Patil). AI Risk Score: 86/100.",
    "mineId": "MINE-01"
  },
  {
    "auditId": "AUD-902",
    "timestamp": "2026-08-26 14:30:00",
    "actor": "Anita Kulkarni (INS-001)",
    "role": "Inspector",
    "action": "INSPECTION_SUBMITTED",
    "details": "Conducted safety inspection INSP-2026-001 in North Shaft. Status: FAILED.",
    "mineId": "MINE-01"
  }
];

export const DEMO_SOS_ALERTS = [
  {
    alertId: "SOS-2026-001",
    inspectorName: "Anita Kulkarni",
    inspectorId: "INS-001",
    mineName: "Demo Mine Alpha",
    mineId: "MINE-01",
    timestamp: "2026-08-28 16:45:12",
    status: "ACKNOWLEDGED",
    alertType: "SOS",
    acknowledgedBy: "Vikram Singh (Officer)",
    acknowledgedTime: "2026-08-28 16:46:05"
  }
];
